services:
  web:
    build: 
      context: .
      dockerfile: Dockerfile
    container_name: service-provider-web
    ports:
      - "8000:8000"
    depends_on:
      - mongodb
    environment:
      - MONGO_URI=mongodb://mongodb:27017
    volumes:
      - ./static:/app/static
      - ./templates:/app/templates
      - ./static/uploads:/app/static/uploads
    restart: always
    networks:
      - app-network

  mongodb:
    image: mongo:latest
    container_name: service-provider-mongodb
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db
    restart: always
    networks:
      - app-network

networks:
  app-network:
    driver: bridge

volumes:
  mongodb_data: 